CREATE INDEX PGInformation$COMPOSITE20 ON PGInformation(employeeUserName)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE UNIQUE INDEX PGInformation$UNIQUE55 ON PGInformation(employeeNo)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
