CREATE INDEX PGMemberLink$COMPOSITE0 ON PGMemberLink(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX PGMemberLink$COMPOSITE1 ON PGMemberLink(idA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
